version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=${MSSQL_PASSWORD}
    links:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y,
      - SA_PASSWORD=${MSSQL_PASSWORD}
